import Link from "next/link";
import { courseSummaries } from "@/lib/course-summaries";

function coursePrice(course: typeof courseSummaries[number]) {
  if (!course.price) return "Price unavailable";
  const amount = Number(course.price.amount) / 10 ** course.price.minorUnit;
  return amount === 0 ? "FREE" : new Intl.NumberFormat("en-IN", { style: "currency", currency: course.price.currency, maximumFractionDigits: amount % 1 ? 2 : 0 }).format(amount);
}

export default function HomePage() {
  const courses = courseSummaries.slice(0, 3);
  return <main className="institution-home premium-home">
      <section className="home-band home-band-library home-entrance-band"><div className="home-inner">
      <section className="home-hero" id="main-content"><div className="home-hero-copy"><p className="eyebrow">Dentomax learning environment</p><h1>A considered place for clinical learning.</h1><p>Discover structured professional course information and access a protected dental reference library—two focused spaces for reading, exploration, and continuing study.</p><div className="landing-actions"><Link className="button" href="/courses">Explore Courses <span>→</span></Link><Link className="button secondary-button" href="/books">Access Book Library <small>Sign in required</small></Link></div><p className="home-hero-note">{courseSummaries.length} published local course records · protected reference access</p></div><div className="home-hero-art" aria-hidden="true"><div className="art-orbit"/><div className="art-book art-book-one">CLINICAL<br/>ATLAS</div><div className="art-book art-book-two">DENTAL<br/>SCIENCE</div><div className="art-book art-book-three">CASE<br/>NOTES</div><span className="art-cross">+</span></div></section>
    </div></section>
      <section className="home-band home-band-academic home-access-band"><div className="home-inner"><section className="home-quick-access" aria-label="Explore Dentomax"><div className="home-section-intro"><p className="eyebrow">Choose a place to begin</p><h2>Built around how you explore knowledge.</h2></div><div className="home-access-panels"><Link href="/courses"><span>01</span><strong>Academic catalogue</strong><small>Search complete, locally presented public course records.</small><b>→</b></Link><Link href="/books"><span>02</span><strong>Digital books</strong><small>Sign in to browse protected references by subject, topic, and file type.</small><b>→</b></Link></div></section></div></section>
    <section className="home-band home-band-paper home-courses-band"><div className="home-inner"><section className="home-course-discovery"><div className="home-section-intro"><p className="eyebrow">Explore medical courses</p><h2>Course information, thoughtfully organised.</h2><p>Read the complete locally stored course information, published topics, and verified public price before you decide what to explore further.</p></div><div className="home-course-grid">{courses.map(course=><article className="home-course-card" key={course.slug}><img src={course.imagePath} alt={course.imageAlt || `${course.title} course`} /><div><p>{course.category}</p><h3>{course.title}</h3><span>{course.durationClaims[0] || "Duration not specified"}</span><strong>{coursePrice(course)}</strong><Link href={`/courses/${course.slug}`}>View course <b>→</b></Link></div></article>)}</div><Link className="home-section-link" href="/courses">View all {courseSummaries.length} courses →</Link></section></div></section>
      <section className="home-band home-library-band"><div className="home-inner"><section className="home-library-intro"><div><p className="eyebrow">The Digital Library</p><h2>Keep essential reference material within reach.</h2><p>Dentomax Library is a protected reading environment for dental resources. Once access is enabled, browse by subject, search resource metadata, save useful references on your device, and read securely in the built-in viewer.</p><div className="landing-actions"><Link className="button" href="/books">Visit Books <span>→</span></Link></div></div><div className="home-library-silhouette" aria-hidden="true"><span>REFERENCE</span><span>CLINICAL</span><span>RESEARCH</span><i/></div></section></div></section>
    <section className="home-band home-journey-band"><div className="home-inner"><section className="home-learning-journey"><div className="home-section-intro"><p className="eyebrow">A focused learning rhythm</p><h2>Discover, read, and return.</h2></div><ol><li><span>01</span><div><h3>Discover</h3><p>Use the academic catalogue or resource search to find a relevant starting point.</p></div></li><li><span>02</span><div><h3>Explore</h3><p>Review published course details or browse protected reference material by subject.</p></div></li><li><span>03</span><div><h3>Keep close</h3><p>Save useful library resources on this device and revisit your reading history.</p></div></li></ol></section></div></section>
    <section className="home-band home-final-band"><div className="home-inner"><section className="home-final-cta"><p className="eyebrow">Dentomax Library</p><h2>Make room for a more considered study practice.</h2><p>Begin with the course catalogue or enter the protected library.</p><div className="landing-actions"><Link className="button" href="/courses">Explore courses <span>→</span></Link><Link className="button secondary-button" href="/books">Access Book Library</Link></div></section></div></section>
  </main>;
}
